### ISSUE TITLE
Two folders contain files with same names but with different content. 

### ISSUE THREAD

**Issue by rei-vilo** [energia/msp432-core#38]
Two folders contain files with same names but with different content. 

* `~/Library/Energia15/packages/energia/hardware/msp432/3.8.0/variants/MSP_EXP432P401R/` (left)
* `~/Library/Energia15/packages/energia/hardware/msp432/3.8.0/cores/msp432/ti/runtime/wiring/msp432/variants/MSP_EXP432P401R/` (right)

<img width="400" alt="capture 2017-02-12 a 18 15 18" src="https://cloud.githubusercontent.com/assets/951776/22864325/9b529486-f14f-11e6-99fb-5e4404bf40a6.png">

A file in red and green means it is missing on the other side, a file in violet means it is different.

Energia takes the files from both folders. How to prevent any conflict?

**Comment by robertinant** [comment]
This should not be there. I just checked the the 3.8.0 package and the only duplicate that I see is the package directory and that should be OK. Did you happen to copy a new package over an older one?

**Comment by rei-vilo** [comment]
Update was carried out through the Boards Manager.

**Comment by rei-vilo** [comment]
I remove the MSP432 package and then performed a fresh install with the Boards Manager. 

Everything goes fine now.
