### ISSUE TITLE
Stream::timedRead hangs in call to HardwareSerial::read

### ISSUE THREAD

**Issue by ablatner** [energia/msp432-core#4]
Stream::timedRead repeatedly calls HardwareSerial::read without checking if a byte is available. The timer is checked in between calls to read, but within read Semaphore_pend is called with a timeout of BIOS_WAIT_FOREVER. This means that timedRead only returns after a byte is received after the timeout expires. In other words, if all data is received within the timeout, timedRead never returns. Checking HardwareSerial::available before calling HardwareSerial::read seems to fix the problem, though there may be a better solution.

**Comment by robertinant** [comment]
This has been fixed and will be available in the next release.
